# extract_pseudo
lch_lower = [20.0, 0.0, 0.0]
lch_upper = [100.0, 120.0, 7.0]
hsv_lower = [35, 40, 50]
hsv_upper = [80, 255, 255]

# grid_view
grid_size = 6

# heatmap_view
kernel_size = 250
density_min = 80  # max: 255
num_density_bins = 4
divided_area = [0,30,170,240,255]

# decide_underpoint
k_h_size = 30
serch_area = [2050,3100]

